CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  "firstName" VARCHAR(40) NOT NULL,
  "lastName" VARCHAR(40) NOT NULL,
  email VARCHAR(200) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user'
      CHECK (role IN ('user', 'admin')),
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
